test to mysql install

diff --git a/shell-script/09-mysql-intall b/shell-script/09-mysql-intall
--- a/shell-script/09-mysql-intall
+++ b/shell-script/09-mysql-intall
@@ -20,3 +20,11 @@ else
 fi
 
 yum install git -y
+
+if [ $? -ne 0 ]
+then
+   echo "ERROR:: Intalling git is failed"
+   exit 1
+   else
+   echo "Installing git is SUCCESS"
+   fi
