test to mysql install

diff --git a/shell-script/09-mysql-intall b/shell-script/09-mysql-intall
--- a/shell-script/09-mysql-intall
+++ b/shell-script/09-mysql-intall
@@ -2,12 +2,11 @@
 ID=$(id -u)
 
 if [ $ID -ne 0 ]
-yum install mysql -y
-
-
 then
-    echo "ERROR:: Installing MySQL is failed"
-    exit 1
+    echo "ERROR:: Please run this script with root access"
+    exit 1 # you can give other than 0
 else
-    echo "Installing MySQL is SUCCESS"
-fi
+    echo "You are root user"
+fi # fi means reverse of if, indicating condition end
+
+yum install mysql -y
