test to mysql install

diff --git a/shell-script/09-mysql-intall b/shell-script/09-mysql-intall
--- a/shell-script/09-mysql-intall
+++ b/shell-script/09-mysql-intall
@@ -10,3 +10,13 @@ else
 fi # fi means reverse of if, indicating condition end
 
 yum install mysql -y
+
+if [ $? -ne 0 ]
+then
+    echo "ERROR:: Installing MySQL is failed"
+    exit 1
+else
+    echo "Installing MySQL is SUCCESS"
+fi
+
+yum install git -y
