test to mysql install

diff --git a/shell-script/10-functions b/shell-script/10-functions
--- a/shell-script/10-functions
+++ b/shell-script/10-functions
@@ -3,7 +3,7 @@ ID=$(id -u)
 
 VALIDATION()
 {
-    if [ $ID -ne 0 ]
+    if [ $ID -ne 0 ] # command line argument $? is used to check the last command execution status, if it is 0 then it is success and if it is other than 0 then it is failed
 then
 echo "ERROR:: please run this script with root accesws"
 exit 1 # you can give other than 0
@@ -12,7 +12,7 @@ echo "You are root user"
 
 fi # fi means reverse of if, indicating condition end
 }
-if [ $? -ne 0 ]
+if [ $? -ne 0 ] # command line argument $? is used to check the last command execution status, if it is 0 then it is success and if it is other than 0 then it is failed
 then 
 echo "ERROR:: Installing MySQL is failed"
 exit 1 # you can give other than 0
