create logs

diff --git a/shell-script/11-logs b/shell-script/11-logs
--- a/shell-script/11-logs
+++ b/shell-script/11-logs
@@ -11,3 +11,13 @@ else
 echo "you are root user"
 fi # fi means reverse of if, indicating condition end
 }
+if [ $? -ne 0 ] # command line argument $? is used to check the last command execution status
+then
+echo "ERROR:: Insttalling mysql is failed"
+exit 1 # you can give other than 0
+else 
+echo "Installing mysql is SUCCESS"
+yum install mysql-server -y $>>logfile
+validation $?
+yum install mysql -y $>>logfile
+validation $?
